### Site Settings ###
title               : Ghaiyur Naqui Ahmad
description         : >- 
                      Python :snake: | Data Science 
                      If you have a problem statement for me , I need to connect with you | I work in Healthcare , AI and everything else !
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Ghaiyur/ghaiyur.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : Ghaiyur/portfolYOU


### Plugins ###
plugins:
  - jemoji
  
  
### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/testblog.md
  - pages/fquotes.md
  - pages/status.md
  - pages/contact.md
  
  
  ### Author Info ###
author:
  name              : Ghaiyur Naqui Ahmad
  image             : ./assets/ghaiyur.jpg
# behance           : your_username
# dribbble          : your_username
  email             : ghaiyur@gmail.com 
# facebook          : your_username
  github            : Ghaiyur
# gitlab            : your_username
# instagram         : your_username
  kaggle            : ghaiyur
  linkedin          : ghaiyur
  medium            : ghaiyur
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : realghaiyur
# vimeo             : your_username
# youtube           : your_channel_name
  quora             : Ghaiyur-Ahmad-1
  resume            : ghaiyur-resume.pdf
